<?php
$data = array (
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '特卖商品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => '特卖商品',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '特价配件',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '特价配件',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '每日10点特价秒杀',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '每日10点特价秒杀',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 0,
    'id' => '5',
    'name' => '配件',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '小米电视与盒子',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '小米电视与盒子',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '小米电视',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '小米电视',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '新小米盒子',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '新小米盒子',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '盒子配件',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '盒子配件',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'PHP源码吧',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => 'PHP源码吧',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '手机外壳',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '手机外壳',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '手机优惠套装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '手机优惠套装',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '红米',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '红米',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '小米2/2S',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '小米2/2S',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '小米2A',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '小米2A',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '小米1/1S',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '小米1/1S',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '软件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '软件',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '按机型选配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '按机型选配件',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '小米1/1S配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '小米1/1S配件',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '红米配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '红米配件',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '小米2/2S配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '小米2/2S配件',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '小米2A配件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '小米2A配件',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '小米手机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '小米手机',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '小米手机1',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '10',
    'name' => '小米手机1',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '小米手机1s',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => '小米手机1s',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '小米手机2',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '小米手机2',
  ),
);
?>