<?php
$data = array (
  0 => 
  array (
    'cat_id' => '38',
    'cat_name' => '商品信息',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'shop',
    'links' => '',
    'sort_order' => '1',
    'weixin_type' => '0',
    'parent_id' => '0',
    'has_children' => '4',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '39',
    'cat_name' => '会员功能',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'member',
    'links' => 'http://xm.58ecshop.co',
    'sort_order' => '2',
    'weixin_type' => '0',
    'parent_id' => '0',
    'has_children' => '5',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '40',
    'cat_name' => '更多..',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'more',
    'links' => '',
    'sort_order' => '3',
    'weixin_type' => '0',
    'parent_id' => '0',
    'has_children' => '5',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '41',
    'cat_name' => '新品上市',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'new',
    'links' => '',
    'sort_order' => '50',
    'weixin_type' => '0',
    'parent_id' => '38',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '42',
    'cat_name' => '精品推荐',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'best',
    'links' => '',
    'sort_order' => '50',
    'weixin_type' => '0',
    'parent_id' => '38',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '43',
    'cat_name' => '热卖商品',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'hot',
    'links' => '',
    'sort_order' => '50',
    'weixin_type' => '0',
    'parent_id' => '38',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '44',
    'cat_name' => '促销活动',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'promote',
    'links' => '',
    'sort_order' => '50',
    'weixin_type' => '0',
    'parent_id' => '38',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  7 => 
  array (
    'cat_id' => '54',
    'cat_name' => '帐户资金',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'jfcx',
    'links' => '',
    'sort_order' => '1',
    'weixin_type' => '0',
    'parent_id' => '39',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  8 => 
  array (
    'cat_id' => '52',
    'cat_name' => '订单查询',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'ddcx',
    'links' => '',
    'sort_order' => '2',
    'weixin_type' => '0',
    'parent_id' => '39',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  9 => 
  array (
    'cat_id' => '53',
    'cat_name' => '快递查询',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'kdcx',
    'links' => '',
    'sort_order' => '3',
    'weixin_type' => '0',
    'parent_id' => '39',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  10 => 
  array (
    'cat_id' => '47',
    'cat_name' => '会员中心',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'member',
    'links' => '',
    'sort_order' => '4',
    'weixin_type' => '0',
    'parent_id' => '39',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  11 => 
  array (
    'cat_id' => '46',
    'cat_name' => '重新绑定',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'cxbd',
    'links' => '',
    'sort_order' => '5',
    'weixin_type' => '0',
    'parent_id' => '39',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  12 => 
  array (
    'cat_id' => '55',
    'cat_name' => '签到',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'qiandao',
    'links' => '',
    'sort_order' => '1',
    'weixin_type' => '0',
    'parent_id' => '40',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  13 => 
  array (
    'cat_id' => '48',
    'cat_name' => '帮助',
    'cat_type' => '1',
    'keywords' => '帮助',
    'weixin_key' => 'help',
    'links' => '',
    'sort_order' => '3',
    'weixin_type' => '0',
    'parent_id' => '40',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  14 => 
  array (
    'cat_id' => '50',
    'cat_name' => '图文消息',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => '图文消息',
    'links' => '',
    'sort_order' => '4',
    'weixin_type' => '0',
    'parent_id' => '40',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  15 => 
  array (
    'cat_id' => '51',
    'cat_name' => '文本消息',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => '文本消息',
    'links' => '',
    'sort_order' => '5',
    'weixin_type' => '0',
    'parent_id' => '40',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  16 => 
  array (
    'cat_id' => '49',
    'cat_name' => '微商城',
    'cat_type' => '1',
    'keywords' => '',
    'weixin_key' => 'index',
    'links' => 'http://shop.hejin.com/xiaomi2014',
    'sort_order' => '50',
    'weixin_type' => '1',
    'parent_id' => '40',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>